return {
  "mfussenegger/nvim-jdtls",
  ft = { "java" },
--  config = function()
--    -- 1. Get the Mason Path
--    local mason_path = vim.fn.stdpath("data") .. "/mason/packages/jdtls"
--    local lombok_path = mason_path .. "/lombok.jar"
--    local config_path = mason_path .. "/config_linux"
--    
--    local launcher_path = vim.fn.glob(mason_path .. "/plugins/org.eclipse.equinox.launcher_*.jar")
--    -- Clean newlines if they exist
--    launcher_path = string.gsub(launcher_path, "\n", "")
--
--    -- 2. Locate the Java Binary (Hardcoded for safety based on your system)
--    local java_bin = "/usr/lib/jvm/java-21-openjdk-amd64/bin/java"
--    if vim.fn.executable(java_bin) ~= 1 then
--      java_bin = "java" -- Fallback
--    end
--
--    -- 3. Create the Autocmd (The Fail-Safe)
--    vim.api.nvim_create_autocmd("FileType", {
--      pattern = "java",
--      callback = function()
--        local jdtls = require("jdtls")
--        local root_markers = { "gradlew", "mvnw", ".git" }
--        local root_dir = require("jdtls.setup").find_root(root_markers)
--        
--        if not root_dir then return end
--
--        local project_name = vim.fn.fnamemodify(root_dir, ":p:h:t")
--        local workspace_dir = vim.fn.expand("~/.cache/jdtls-workspace/") .. project_name
--
--        -- 4. The Command with Lombok
--        local cmd = {
--          java_bin,
--          "-Declipse.application=org.eclipse.jdt.ls.core.id1",
--          "-Dosgi.bundles.defaultStartLevel=4",
--          "-Declipse.product=org.eclipse.jdt.ls.core.product",
--          "-Dosgi.checkConfiguration=true",
--          "-Dosgi.sharedConfiguration.area=" .. config_path,
--          "-Dosgi.sharedConfiguration.area.readOnly=true",
--          "-Dosgi.configuration.cascaded=true",
--          "-Xms1g",
--          "--add-modules=ALL-SYSTEM",
--          "--add-opens", "java.base/java.util=ALL-UNNAMED",
--          "--add-opens", "java.base/java.lang=ALL-UNNAMED",
--          
--          -- ✅ LOMBOK AGENT
--          "-javaagent:" .. lombok_path,
--          
--          "-jar", launcher_path,
--          "-configuration", config_path,
--          "-data", workspace_dir,
--        }
--
--        local config = {
--          cmd = cmd,
--          root_dir = root_dir,
--          capabilities = require("cmp_nvim_lsp").default_capabilities(),
--          settings = {
--            java = {
--              configuration = {
--                runtimes = {
--                  {
--                    name = "JavaSE-21",
--                    path = "/usr/lib/jvm/java-21-openjdk-amd64",
--                  },
--                },
--              },
--            },
--          },
--        }
--
--        -- 5. Start JDTLS
--        jdtls.start_or_attach(config)
--      end,
--    })
--  end,
}
